### ISSUE TITLE
Cannot find the file  ‘gen_pretrain_feature.py’

### ISSUE THREAD

**Issue by djs1014** [VT-NLP/ICE#1]
Hello, I cannot find the file 'gen_pretrain_feature.py', is it in another project or something, Thanks!

**Comment by mqianliu** [comment]
Hi, thanks for spotting this issue. I have uploaded the gen_pretrain_feature.py in the repo.

**Comment by djs1014** [comment]
Hello, thank you for your reply! The MAVEN dataset cannot be processed according to the 'gen_pretrain_feature' file you provided. Lines 69 and 70 of the file show the keys "sentence_id" and "piece_ids", but these keywords are not in the MAVEN dataset.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VT-NLP/ICE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月25日(星期五) 凌晨4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VT-NLP/ICE] Cannot find the file  ‘gen_pretrain_feature.py’ (Issue #1)





 
Hi, thanks for spotting this issue. I have uploaded the gen_pretrain_feature.py in the repo.
