### ISSUE TITLE
 MAVEN dataset cannot be processed by  'gen_pretrain_feature.py'

### ISSUE THREAD

**Issue by djs1014** [VT-NLP/ICE#2]
Hello, The MAVEN dataset cannot be processed according to the 'gen_pretrain_feature' file you provided. Lines 69 and 70 of the file show the keys "sentence_id" and "piece_ids", but these keywords are not in the MAVEN dataset. Looking forward to your reply！

**Comment by mqianliu** [comment]
Hi,

We've uploaded the preprocessed dataset in this [Google Drive link](https://drive.google.com/drive/folders/1nbQLBXMq6rfat7GAkGml_Wli9CyOtWWb?usp=sharing). You can use these preprocessed files to generate the contextualized features. We also uploaded the link in the README.

Hope this help. Thanks.
