### ISSUE TITLE
Missing intermediate files

### ISSUE THREAD

**Issue by djs1014** [VT-NLP/ICE#3]
Following README, I try to run './scripts/run_main.sh', I find that there is no path './data/features/MAVEN' and no files './data/MAVEN/streams.json', './data/MAVEN/id2tokens.json', './data/MAVEN/label2id.json'.  I also get an error when I try to generate 'streams.json' by running 'prepare_streams.py', and I'm confused by the lack of these files

**Comment by mqianliu** [comment]
Hi, I've uploaded the intermediate files to `data` folder. Pls check it out.
